Stops if stdc++ library not found

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3244,6 +3244,10 @@ _ACEOF
 
   LIBS="-lstdc++ $LIBS"
 
+else
+  { { echo "$as_me:$LINENO: error: library stdc++ is not found..." >&5
+echo "$as_me: error: library stdc++ is not found..." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
